name: Kidsffw CI/CD
on:
  push:
    branches: [ "test","main" ]
  pull_request:
    branches: [ "test", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4
    - name: print Branch Name 
      run: echo ${{steps.branch-name.outputs.current_branch}}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build Test
      if: ${{steps.branch-name.outputs.current_branch}} == "test"
      run: dotnet build -c debug --no-restore
      # run: dotnet build -c debug --no-restore
    - name: build Release
      if: ${{steps.branch-name.outputs.current_branch}} == "main"
      run: dotnet build -c release --no-restore
    - name: Publish Test Application
      if: ${{steps.branch-name.outputs.current_branch}} == "test"
      run: dotnet publish -c debug
    - name: Publish Release Application
      if: ${{steps.branch-name.outputs.current_branch}} == "main"
      run: dotnet publish -c release
      
    - name: Upload API Artifact
      uses: actions/upload-artifact@v2
      with:
        name: kidsffw.test
        path: /home/runner/work/kidsffw-registration/kidsffw-registration/kidsffw.Api/bin/Debug/net6.0/publish/

      
